using System.Collections.Generic;
using System.IO;

namespace MvcMovie.Models
{
    public static class MoviePosters
    {
        private static readonly Dictionary<string, string> Local = new Dictionary<string, string>
        {
            { "When Harry Met Sally", "/images/posters/poster-001.jpg" },
            { "Ghostbusters 2", "/images/posters/poster-002.jpg" },
            { "Rio Bravo", "/images/posters/poster-003.jpg" },
            { "Top Gun: Maverick", "/images/posters/poster-004.jpg" },
            { "The Matrix", "/images/posters/poster-005.png" },
            { "Interstellar", "/images/posters/poster-006.jpg" },
            { "Die Hard", "/images/posters/poster-007.jpg" },
            { "Jurassic Park", "/images/posters/poster-008.jpg" },
            { "Paddington 2", "/images/posters/poster-009.jpg" },
            { "The Dark Knight", "/images/posters/poster-010.jpg" },
            { "Shrek 2", "/images/posters/poster-011.jpg" },
            { "A Crown for Christmas", "/images/posters/poster-012.jpg" },
            { "A Christmas Prince", "/images/posters/poster-013.png" },
            { "Inception", "/images/posters/poster-014.jpg" },
            { "Gladiator", "/images/posters/poster-015.png" },
            { "Titanic", "/images/posters/poster-016.png" },
            { "The Lord of the Rings: The Fellowship of the Ring", "/images/posters/poster-017.jpg" },
            { "Avatar", "/images/posters/poster-018.jpg" },
            { "Star Wars: Episode IV - A New Hope", "/images/posters/poster-019.jpg" },
            { "Pulp Fiction", "/images/posters/poster-020.jpg" },
            { "Fight Club", "/images/posters/poster-021.jpg" },
            { "Forrest Gump", "/images/posters/poster-022.jpg" },
            { "The Godfather", "/images/posters/poster-023.jpg" },
            { "The Silence of the Lambs", "/images/posters/poster-024.jpg" },
            { "Saving Private Ryan", "/images/posters/poster-025.jpg" },
            { "The Departed", "/images/posters/poster-026.jpg" },
            { "Whiplash", "/images/posters/poster-027.jpg" },
            { "The Prestige", "/images/posters/poster-028.jpg" },
            { "Memento", "/images/posters/poster-029.jpg" },
            { "The Lion King", "/images/posters/poster-030.jpg" },
            { "Toy Story", "/images/posters/poster-031.jpg" },
            { "Finding Nemo", "/images/posters/poster-032.jpg" },
            { "Up", "/images/posters/poster-033.jpg" },
            { "WALL-E", "/images/posters/poster-034.jpg" },
            { "Spider-Man: Into the Spider-Verse", "/images/posters/poster-035.png" },
            { "Spider-Man: Across the Spider-Verse", "/images/posters/poster-036.jpg" },
            { "The Avengers", "/images/posters/poster-037.jpg" },
            { "Iron Man", "/images/posters/poster-038.jpg" },
            { "Captain America: The Winter Soldier", "/images/posters/poster-039.jpg" },
            { "Logan", "/images/posters/poster-040.jpg" },
            { "Blade Runner 2049", "/images/posters/poster-041.png" },
            { "Arrival", "/images/posters/poster-042.jpg" },
            { "Dune: Part One", "/images/posters/poster-043.jpg" },
            { "Dune: Part Two", "/images/posters/poster-044.jpeg" },
            { "Mad Max: Fury Road", "/images/posters/poster-045.jpg" },
            { "John Wick", "/images/posters/poster-046.jpg" },
            { "Baby Driver", "/images/posters/poster-047.jpg" },
            { "Knives Out", "/images/posters/poster-048.jpeg" },
            { "Glass Onion", "/images/posters/poster-049.jpg" },
            { "Parasite", "/images/posters/poster-050.png" },
            { "Everything Everywhere All at Once", "/images/posters/poster-051.jpg" },
            { "La La Land", "/images/posters/poster-052.png" },
            { "The Truman Show", "/images/posters/poster-053.jpg" },
            { "Back to the Future", "/images/posters/poster-054.jpg" },
            { "Ghostbusters", "/images/posters/poster-055.png" },
            { "The Goonies", "/images/posters/poster-056.jpg" },
            { "E.T. the Extra-Terrestrial", "/images/posters/poster-057.jpg" },
            { "Jaws", "/images/posters/poster-058.jpg" },
            { "Alien", "/images/posters/poster-059.jpg" },
            { "The Thing", "/images/posters/poster-060.png" },
            { "The Shining", "/images/posters/poster-061.jpg" },
            { "Hereditary", "/images/posters/poster-062.png" },
            { "Get Out", "/images/posters/poster-063.png" },
            { "A Quiet Place", "/images/posters/poster-064.png" },
            { "Superbad", "/images/posters/poster-065.png" },
            { "Step Brothers", "/images/posters/poster-066.jpg" },
            { "Anchorman", "/images/posters/poster-067.jpg" },
            { "Tropic Thunder", "/images/posters/poster-068.jpg" },
            { "Hot Fuzz", "/images/posters/poster-069.jpg" },
            { "Shaun of the Dead", "/images/posters/poster-070.jpg" },
            { "The Grand Budapest Hotel", "/images/posters/poster-071.png" },
            { "Knocked Up", "/images/posters/poster-072.jpg" },
            { "Mean Girls", "/images/posters/poster-073.png" },
            { "Clueless", "/images/posters/poster-074.png" },
            { "10 Things I Hate About You", "/images/posters/poster-075.jpg" },
            { "The Notebook", "/images/posters/poster-076.jpg" },
            { "Pride and Prejudice", "/images/posters/poster-077.jpg" },
            { "About Time", "/images/posters/poster-078.jpg" },
            { "Little Women", "/images/posters/poster-079.jpeg" },
            { "Lady Bird", "/images/posters/poster-080.jpeg" },
            { "The Social Network", "/images/posters/poster-081.png" },
            { "Moneyball", "/images/posters/poster-082.jpg" },
            { "The Wolf of Wall Street", "/images/posters/poster-083.png" },
            { "Catch Me If You Can", "/images/posters/poster-084.jpg" },
            { "Zootopia", "/images/posters/poster-085.jpg" },
            { "Moana", "/images/posters/poster-086.jpg" },
            { "Frozen", "/images/posters/poster-087.jpg" },
            { "Tangled", "/images/posters/poster-088.jpg" },
            { "Ratatouille", "/images/posters/poster-089.jpg" },
            { "The Incredibles", "/images/posters/poster-090.jpg" },
            { "Monsters, Inc.", "/images/posters/poster-091.JPG" },
            { "Princess Switch", "/images/posters/poster-092.png" },
            { "The Knight Before Christmas", "/images/posters/poster-093.jpg" },
            { "Operation Christmas Drop", "/images/posters/poster-094.png" },
            { "Christmas Inheritance", "/images/posters/poster-095.png" },
            { "Holidate", "/images/posters/poster-096.png" },
            { "Love Hard", "/images/posters/poster-097.jpg" },
            { "Falling for Christmas", "/images/posters/poster-098.png" },
            { "Hot Frosty", "/images/posters/poster-099.jpg" },
            { "The Merry Gentlemen", "/images/posters/poster-100.jpg" },
            { "The Exorcist", "/images/posters/poster-101.jpg" },
            { "Halloween", "/images/posters/poster-102.jpg" },
            { "Scream", "/images/posters/poster-103.jpg" },
            { "A Nightmare on Elm Street", "/images/posters/poster-104.jpg" },
            { "Friday the 13th", "/images/posters/poster-105.jpg" },
            { "Psycho", "/images/posters/poster-106.jpg" },
            { "The Ring", "/images/posters/poster-107.jpg" },
            { "The Grudge", "/images/posters/poster-108.jpg" },
            { "Saw", "/images/posters/poster-109.jpg" },
            { "The Texas Chainsaw Massacre", "/images/posters/poster-110.jpg" },
            { "Rosemary's Baby", "/images/posters/poster-111.jpg" },
            { "The Blair Witch Project", "/images/posters/poster-112.jpg" },
            { "The Conjuring", "/images/posters/poster-113.jpg" },
            { "Insidious", "/images/posters/poster-114.jpg" },
            { "It", "/images/posters/poster-115.jpg" },
            { "Us", "/images/posters/poster-116.png" },
            { "Midsommar", "/images/posters/poster-117.png" },
            { "The Witch", "/images/posters/poster-118.png" },
            { "The Martian", "/images/posters/poster-119.jpg" },
            { "Project Hail Mary", "/images/posters/poster-120.jpg" },
            { "Men in Black", "/images/posters/poster-121.jpg" },
            { "Gravity", "/images/posters/poster-122.jpg" },
            { "Sunshine", "/images/posters/poster-123.jpg" },
            { "Moon", "/images/posters/poster-124.jpg" },
            { "Ex Machina", "/images/posters/poster-125.jpg" },
            { "Her", "/images/posters/poster-126.jpg" },
            { "The Fifth Element", "/images/posters/poster-127.jpg" },
            { "Total Recall", "/images/posters/poster-128.jpg" },
            { "The Terminator", "/images/posters/poster-129.png" },
            { "Terminator 2: Judgment Day", "/images/posters/poster-130.png" },
            { "Edge of Tomorrow", "/images/posters/poster-131.jpg" },
            { "Minority Report", "/images/posters/poster-132.jpg" },
            { "The Hunger Games", "/images/posters/poster-133.jpg" },
            { "Se7en", "/images/posters/poster-134.jpg" },
            { "Zodiac", "/images/posters/poster-135.jpg" },
            { "Shutter Island", "/images/posters/poster-136.jpg" },
            { "The Usual Suspects", "/images/posters/poster-137.jpg" },
            { "No Country for Old Men", "/images/posters/poster-138.jpg" },
            { "Goodfellas", "/images/posters/poster-139.jpg" },
            { "Reservoir Dogs", "/images/posters/poster-140.png" },
            { "Heat", "/images/posters/poster-141.jpg" },
            { "Gone Girl", "/images/posters/poster-142.jpg" },
            { "Prisoners", "/images/posters/poster-143.jpg" },
            { "The Menu", "/images/posters/poster-144.jpg" },
            { "The Shawshank Redemption", "/images/posters/poster-145.jpg" },
            { "Schindler's List", "/images/posters/poster-146.jpg" },
            { "The Green Mile", "/images/posters/poster-147.jpg" },
            { "Good Will Hunting", "/images/posters/poster-148.png" },
            { "Dead Poets Society", "/images/posters/poster-149.png" },
            { "A Beautiful Mind", "/images/posters/poster-150.jpg" },
            { "Oppenheimer", "/images/posters/poster-151.jpg" },
            { "Dunkirk", "/images/posters/poster-152.jpg" },
            { "1917", "/images/posters/poster-153.jpeg" },
            { "Full Metal Jacket", "/images/posters/poster-154.jpg" },
            { "Apocalypse Now", "/images/posters/poster-155.jpg" },
            { "Hacksaw Ridge", "/images/posters/poster-156.png" },
            { "The Revenant", "/images/posters/poster-157.jpg" },
            { "Into the Wild", "/images/posters/poster-158.png" },
            { "Cast Away", "/images/posters/poster-159.jpg" },
            { "Life of Pi", "/images/posters/poster-160.png" },
            { "Spirited Away", "/images/posters/poster-161.png" },
            { "Howl's Moving Castle", "/images/posters/poster-162.jpg" },
            { "My Neighbor Totoro", "/images/posters/poster-163.jpg" },
            { "Princess Mononoke", "/images/posters/poster-164.png" },
            { "The Iron Giant", "/images/posters/poster-165.JPG" },
            { "Coraline", "/images/posters/poster-166.jpg" },
            { "Despicable Me", "/images/posters/poster-167.png" },
            { "Inside Out", "/images/posters/poster-168.jpg" },
            { "Coco", "/images/posters/poster-169.jpg" },
            { "Casino Royale", "/images/posters/poster-170.jpg" },
            { "Skyfall", "/images/posters/poster-171.jpg" },
            { "Mission: Impossible - Fallout", "/images/posters/poster-172.jpg" },
            { "The Bourne Identity", "/images/posters/poster-173.jpg" },
            { "Taken", "/images/posters/poster-174.jpg" },
            { "The Equalizer", "/images/posters/poster-175.jpg" },
            { "John Wick: Chapter 2", "/images/posters/poster-176.png" },
            { "Speed", "/images/posters/poster-177.jpg" },
            { "Lethal Weapon", "/images/posters/poster-178.jpg" },
            { "Predator", "/images/posters/poster-179.jpg" },
            { "Crazy Rich Asians", "/images/posters/poster-180.png" },
            { "The Proposal", "/images/posters/poster-181.jpg" },
            { "500 Days of Summer", "/images/posters/poster-182.jpg" },
            { "Silver Linings Playbook", "/images/posters/poster-183.jpg" },
            { "Eternal Sunshine of the Spotless Mind", "/images/posters/poster-184.png" },
            { "The Fault in Our Stars", "/images/posters/poster-185.jpg" },
            { "Me Before You", "/images/posters/poster-186.jpg" },
            { "Crazy, Stupid, Love", "/images/posters/poster-187.jpg" },
            { "Bridesmaids", "/images/posters/poster-188.jpg" },
            { "The Hangover", "/images/posters/poster-189.jpg" },
            { "21 Jump Street", "/images/posters/poster-190.png" },
            { "Deadpool", "/images/posters/poster-191.png" },
            { "The 40-Year-Old Virgin", "/images/posters/poster-192.jpg" },
            { "Talladega Nights", "/images/posters/poster-193.jpg" },
            { "Elf", "/images/posters/poster-194.jpg" },
            { "Groundhog Day", "/images/posters/poster-195.jpg" },
            { "The Breakfast Club", "/images/posters/poster-196.jpg" },
            { "Ferris Bueller's Day Off", "/images/posters/poster-197.jpg" },
            { "Juno", "/images/posters/poster-198.png" },
            { "Little Miss Sunshine", "/images/posters/poster-199.jpg" },
            { "The Big Lebowski", "/images/posters/poster-200.jpg" },
            { "Gunpowder Milkshake", "/images/posters/poster-201.jpeg" },
            { "The Girl with All the Gifts", "/images/posters/poster-202.jpg" },
            { "Midori", "/images/posters/poster-203.jpg" },
            { "A Serbian Film", "/images/posters/poster-204.jpg" },
            { "Salò, or the 120 Days of Sodom", "/images/posters/poster-205.jpg" },
            { "Cannibal Holocaust", "/images/posters/poster-206.jpg" },
            { "Akira", "/images/posters/poster-207.jpg" },
            { "Ghost in the Shell", "/images/posters/poster-208.jpg" },
            { "Your Name", "/images/posters/poster-209.png" },
            { "Perfect Blue", "/images/posters/poster-210.png" },
            { "Paprika", "/images/posters/poster-211.jpg" },
            { "The End of Evangelion", "/images/posters/poster-212.JPG" },
            { "Grave of the Fireflies", "/images/posters/poster-213.jpg" },
            { "Nausicaä of the Valley of the Wind", "/images/posters/poster-214.jpg" },
            { "Kiki's Delivery Service", "/images/posters/poster-215.jpg" },
            { "Ponyo", "/images/posters/poster-216.png" },
        };

        private static readonly Dictionary<string, string> Remote = new Dictionary<string, string>
        {
            { "When Harry Met Sally", "https://upload.wikimedia.org/wikipedia/en/1/1c/WhenHarryMetSallyPoster.jpg" },
            { "Ghostbusters 2", "https://upload.wikimedia.org/wikipedia/en/0/01/Ghostbusters_ii_poster.jpg" },
            { "Rio Bravo", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Rio_Bravo_%281959_poster%29.jpg/330px-Rio_Bravo_%281959_poster%29.jpg" },
            { "Top Gun: Maverick", "https://upload.wikimedia.org/wikipedia/en/1/13/Top_Gun_Maverick_Poster.jpg" },
            { "The Matrix", "https://upload.wikimedia.org/wikipedia/en/d/db/The_Matrix.png" },
            { "Interstellar", "https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg" },
            { "Die Hard", "https://upload.wikimedia.org/wikipedia/en/c/ca/Die_Hard_%281988_film%29_poster.jpg" },
            { "Jurassic Park", "https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg" },
            { "Paddington 2", "https://upload.wikimedia.org/wikipedia/en/b/b6/Paddington_2_poster.jpg" },
            { "The Dark Knight", "https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg" },
            { "Shrek 2", "https://upload.wikimedia.org/wikipedia/en/b/b9/Shrek_2_poster.jpg" },
            { "A Crown for Christmas", "https://media.themoviedb.org/t/p/w342/7lRL9n6Zvvl7BMpGzELvzWJx2df.jpg" },
            { "A Christmas Prince", "https://upload.wikimedia.org/wikipedia/en/9/91/A_Christmas_Prince.png" },
            { "Inception", "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg" },
            { "Gladiator", "https://upload.wikimedia.org/wikipedia/en/f/fb/Gladiator_%282000_film_poster%29.png" },
            { "Titanic", "https://upload.wikimedia.org/wikipedia/en/1/18/Titanic_%281997_film%29_poster.png" },
            { "The Lord of the Rings: The Fellowship of the Ring", "https://upload.wikimedia.org/wikipedia/en/f/fb/Lord_Rings_Fellowship_Ring.jpg" },
            { "Avatar", "https://upload.wikimedia.org/wikipedia/en/d/d6/Avatar_%282009_film%29_poster.jpg" },
            { "Star Wars: Episode IV - A New Hope", "https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg" },
            { "Pulp Fiction", "https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg" },
            { "Fight Club", "https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg" },
            { "Forrest Gump", "https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg" },
            { "The Godfather", "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg" },
            { "The Silence of the Lambs", "https://upload.wikimedia.org/wikipedia/en/8/86/The_Silence_of_the_Lambs_poster.jpg" },
            { "Saving Private Ryan", "https://upload.wikimedia.org/wikipedia/en/a/ac/Saving_Private_Ryan_poster.jpg" },
            { "The Departed", "https://upload.wikimedia.org/wikipedia/en/5/50/Departed234.jpg" },
            { "Whiplash", "https://upload.wikimedia.org/wikipedia/en/0/01/Whiplash_poster.jpg" },
            { "The Prestige", "https://upload.wikimedia.org/wikipedia/en/d/d2/Prestige_poster.jpg" },
            { "Memento", "https://upload.wikimedia.org/wikipedia/en/c/c7/Memento_poster.jpg" },
            { "The Lion King", "https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg" },
            { "Toy Story", "https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg" },
            { "Finding Nemo", "https://upload.wikimedia.org/wikipedia/en/2/29/Finding_Nemo.jpg" },
            { "Up", "https://upload.wikimedia.org/wikipedia/en/0/05/Up_%282009_film%29.jpg" },
            { "WALL-E", "https://upload.wikimedia.org/wikipedia/en/4/4c/WALL-E_poster.jpg" },
            { "Spider-Man: Into the Spider-Verse", "https://upload.wikimedia.org/wikipedia/en/f/fa/Spider-Man_Into_the_Spider-Verse_poster.png" },
            { "Spider-Man: Across the Spider-Verse", "https://upload.wikimedia.org/wikipedia/en/b/b4/Spider-Man-_Across_the_Spider-Verse_poster.jpg" },
            { "The Avengers", "https://upload.wikimedia.org/wikipedia/en/8/8a/The_Avengers_%282012_film%29_poster.jpg" },
            { "Iron Man", "https://upload.wikimedia.org/wikipedia/en/0/02/Iron_Man_%282008_film%29_poster.jpg" },
            { "Captain America: The Winter Soldier", "https://upload.wikimedia.org/wikipedia/en/9/9e/Captain_America_The_Winter_Soldier_poster.jpg" },
            { "Logan", "https://upload.wikimedia.org/wikipedia/en/3/37/Logan_2017_poster.jpg" },
            { "Blade Runner 2049", "https://upload.wikimedia.org/wikipedia/en/9/9b/Blade_Runner_2049_poster.png" },
            { "Arrival", "https://upload.wikimedia.org/wikipedia/en/d/df/Arrival%2C_Movie_Poster.jpg" },
            { "Dune: Part One", "https://upload.wikimedia.org/wikipedia/en/8/8e/Dune_%282021_film%29.jpg" },
            { "Dune: Part Two", "https://upload.wikimedia.org/wikipedia/en/5/52/Dune_Part_Two_poster.jpeg" },
            { "Mad Max: Fury Road", "https://upload.wikimedia.org/wikipedia/en/6/6e/Mad_Max_Fury_Road.jpg" },
            { "John Wick", "https://upload.wikimedia.org/wikipedia/en/9/98/John_Wick_TeaserPoster.jpg" },
            { "Baby Driver", "https://upload.wikimedia.org/wikipedia/en/8/8e/Baby_Driver_poster.jpg" },
            { "Knives Out", "https://upload.wikimedia.org/wikipedia/en/1/1f/Knives_Out_poster.jpeg" },
            { "Glass Onion", "https://upload.wikimedia.org/wikipedia/en/6/62/Glass_Onion_poster.jpg" },
            { "Parasite", "https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29.png" },
            { "Everything Everywhere All at Once", "https://upload.wikimedia.org/wikipedia/en/1/1e/Everything_Everywhere_All_at_Once.jpg" },
            { "La La Land", "https://upload.wikimedia.org/wikipedia/en/a/ab/La_La_Land_%28film%29.png" },
            { "The Truman Show", "https://upload.wikimedia.org/wikipedia/en/c/cd/Trumanshow.jpg" },
            { "Back to the Future", "https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg" },
            { "Ghostbusters", "https://upload.wikimedia.org/wikipedia/en/2/2f/Ghostbusters_%281984%29_theatrical_poster.png" },
            { "The Goonies", "https://upload.wikimedia.org/wikipedia/en/c/c6/The_Goonies.jpg" },
            { "E.T. the Extra-Terrestrial", "https://upload.wikimedia.org/wikipedia/en/6/66/E_t_the_extra_terrestrial_ver3.jpg" },
            { "Jaws", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Jaws_movie_poster.jpg/330px-Jaws_movie_poster.jpg" },
            { "Alien", "https://upload.wikimedia.org/wikipedia/en/c/c3/Alien_movie_poster.jpg" },
            { "The Thing", "https://upload.wikimedia.org/wikipedia/en/e/e3/The_Thing_%281982_film%29.png" },
            { "The Shining", "https://upload.wikimedia.org/wikipedia/en/1/1d/The_Shining_%281980%29_U.K._release_poster_-_The_tide_of_terror_that_swept_America_IS_HERE.jpg" },
            { "Hereditary", "https://upload.wikimedia.org/wikipedia/en/d/d9/Hereditary.png" },
            { "Get Out", "https://upload.wikimedia.org/wikipedia/en/a/a3/Get_Out_poster.png" },
            { "A Quiet Place", "https://upload.wikimedia.org/wikipedia/en/a/a0/A_Quiet_Place_film_poster.png" },
            { "Superbad", "https://upload.wikimedia.org/wikipedia/en/8/8b/Superbad_Poster.png" },
            { "Step Brothers", "https://upload.wikimedia.org/wikipedia/en/d/d9/StepbrothersMP08.jpg" },
            { "Anchorman", "https://upload.wikimedia.org/wikipedia/en/6/64/Movie_poster_Anchorman_The_Legend_of_Ron_Burgundy.jpg" },
            { "Tropic Thunder", "https://upload.wikimedia.org/wikipedia/en/d/d6/Tropic_thunder_ver3.jpg" },
            { "Hot Fuzz", "https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/HotFuzzUKposter.jpg/330px-HotFuzzUKposter.jpg" },
            { "Shaun of the Dead", "https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/Shaun_of_the_Dead_film_poster.jpg/330px-Shaun_of_the_Dead_film_poster.jpg" },
            { "The Grand Budapest Hotel", "https://upload.wikimedia.org/wikipedia/en/1/1c/The_Grand_Budapest_Hotel.png" },
            { "Knocked Up", "https://upload.wikimedia.org/wikipedia/en/5/51/Knockedupmp.jpg" },
            { "Mean Girls", "https://upload.wikimedia.org/wikipedia/en/a/ac/Mean_Girls_film_poster.png" },
            { "Clueless", "https://upload.wikimedia.org/wikipedia/en/5/5a/Clueless_film_poster.png" },
            { "10 Things I Hate About You", "https://upload.wikimedia.org/wikipedia/en/9/95/10_Things_I_Hate_About_You_film.jpg" },
            { "The Notebook", "https://upload.wikimedia.org/wikipedia/en/8/86/Posternotebook.jpg" },
            { "Pride and Prejudice", "https://upload.wikimedia.org/wikipedia/en/0/03/Prideandprejudiceposter.jpg" },
            { "About Time", "https://upload.wikimedia.org/wikipedia/en/7/7c/About_Time_%282013_film%29_Poster.jpg" },
            { "Little Women", "https://upload.wikimedia.org/wikipedia/en/9/9d/Little_Women_%282019_film%29.jpeg" },
            { "Lady Bird", "https://upload.wikimedia.org/wikipedia/en/6/61/Lady_Bird_poster.jpeg" },
            { "The Social Network", "https://upload.wikimedia.org/wikipedia/en/8/8c/The_Social_Network_film_poster.png" },
            { "Moneyball", "https://upload.wikimedia.org/wikipedia/en/2/2e/Moneyball_Poster.jpg" },
            { "The Wolf of Wall Street", "https://upload.wikimedia.org/wikipedia/en/d/d8/The_Wolf_of_Wall_Street_%282013%29.png" },
            { "Catch Me If You Can", "https://upload.wikimedia.org/wikipedia/en/4/4d/Catch_Me_If_You_Can_2002_movie.jpg" },
            { "Zootopia", "https://upload.wikimedia.org/wikipedia/en/9/96/Zootopia_%28movie_poster%29.jpg" },
            { "Moana", "https://upload.wikimedia.org/wikipedia/en/2/26/Moana_Teaser_Poster.jpg" },
            { "Frozen", "https://upload.wikimedia.org/wikipedia/en/0/05/Frozen_%282013_film%29_poster.jpg" },
            { "Tangled", "https://upload.wikimedia.org/wikipedia/en/a/a8/Tangled_poster.jpg" },
            { "Ratatouille", "https://upload.wikimedia.org/wikipedia/en/5/50/RatatouillePoster.jpg" },
            { "The Incredibles", "https://upload.wikimedia.org/wikipedia/en/2/27/The_Incredibles_%282004_animated_feature_film%29.jpg" },
            { "Monsters, Inc.", "https://upload.wikimedia.org/wikipedia/en/6/63/Monsters_Inc.JPG" },
            { "Princess Switch", "https://upload.wikimedia.org/wikipedia/en/2/2e/The_Princess_Switch.png" },
            { "The Knight Before Christmas", "https://upload.wikimedia.org/wikipedia/en/a/aa/The_Knight_Before_Christmas_poster.jpg" },
            { "Operation Christmas Drop", "https://upload.wikimedia.org/wikipedia/en/7/7a/Operation_Christmas_Drop_film_poster.png" },
            { "Christmas Inheritance", "https://upload.wikimedia.org/wikipedia/en/4/41/Christmas_Inheritance.png" },
            { "Holidate", "https://upload.wikimedia.org/wikipedia/en/0/01/Holidate_film_poster.png" },
            { "Love Hard", "https://upload.wikimedia.org/wikipedia/en/f/f6/Love_Hard_poster.jpg" },
            { "Falling for Christmas", "https://upload.wikimedia.org/wikipedia/en/3/35/Falling_for_Christmas_poster.png" },
            { "Hot Frosty", "https://upload.wikimedia.org/wikipedia/en/4/47/Hot_Frosty.jpg" },
            { "The Merry Gentlemen", "https://upload.wikimedia.org/wikipedia/en/a/af/The_Merry_Gentlemen.jpg" },
            { "The Exorcist", "https://upload.wikimedia.org/wikipedia/en/7/7b/Exorcist_ver2.jpg" },
            { "Halloween", "https://upload.wikimedia.org/wikipedia/en/a/af/Halloween_%281978%29_theatrical_poster.jpg" },
            { "Scream", "https://upload.wikimedia.org/wikipedia/en/8/86/Scream_%281996_film%29_poster.jpg" },
            { "A Nightmare on Elm Street", "https://upload.wikimedia.org/wikipedia/en/f/fa/A_Nightmare_on_Elm_Street_%281984%29_theatrical_poster.jpg" },
            { "Friday the 13th", "https://upload.wikimedia.org/wikipedia/en/2/2c/Friday_the_13th_%281980%29_theatrical_poster.jpg" },
            { "Psycho", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Psycho_%281960%29_theatrical_poster_%28retouched%29.jpg/330px-Psycho_%281960%29_theatrical_poster_%28retouched%29.jpg" },
            { "The Ring", "https://upload.wikimedia.org/wikipedia/en/3/37/Theringpostere.jpg" },
            { "The Grudge", "https://upload.wikimedia.org/wikipedia/en/9/91/The_Grudge_movie.jpg" },
            { "Saw", "https://upload.wikimedia.org/wikipedia/en/5/56/Saw_official_poster.jpg" },
            { "The Texas Chainsaw Massacre", "https://upload.wikimedia.org/wikipedia/en/a/a0/The_Texas_Chain_Saw_Massacre_%281974%29_theatrical_poster.jpg" },
            { "Rosemary's Baby", "https://upload.wikimedia.org/wikipedia/en/e/ef/Rosemarys_baby_poster.jpg" },
            { "The Blair Witch Project", "https://upload.wikimedia.org/wikipedia/en/2/26/Blair_Witch_Project.jpg" },
            { "The Conjuring", "https://upload.wikimedia.org/wikipedia/en/8/8c/The_Conjuring_poster.jpg" },
            { "Insidious", "https://upload.wikimedia.org/wikipedia/en/2/2d/Insidious_poster.jpg" },
            { "It", "https://upload.wikimedia.org/wikipedia/en/5/5a/It_%282017%29_poster.jpg" },
            { "Us", "https://upload.wikimedia.org/wikipedia/en/0/00/Us_%282019%29_theatrical_poster.png" },
            { "Midsommar", "https://upload.wikimedia.org/wikipedia/en/4/47/Midsommar_%282019_film_poster%29.png" },
            { "The Witch", "https://upload.wikimedia.org/wikipedia/en/b/bf/The_Witch_poster.png" },
            { "The Martian", "https://upload.wikimedia.org/wikipedia/en/c/cd/The_Martian_film_poster.jpg" },
            { "Project Hail Mary", "https://upload.wikimedia.org/wikipedia/en/3/3b/Project_Hail_Mary_poster.jpg" },
            { "Men in Black", "https://upload.wikimedia.org/wikipedia/en/f/fb/Men_in_Black_Poster.jpg" },
            { "Gravity", "https://upload.wikimedia.org/wikipedia/en/f/f6/Gravity_Poster.jpg" },
            { "Sunshine", "https://upload.wikimedia.org/wikipedia/en/thumb/6/68/Sunshine_poster.jpg/330px-Sunshine_poster.jpg" },
            { "Moon", "https://upload.wikimedia.org/wikipedia/en/a/af/Moon_%282009_film%29.jpg" },
            { "Ex Machina", "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Ex-machina-uk-poster.jpg/330px-Ex-machina-uk-poster.jpg" },
            { "Her", "https://upload.wikimedia.org/wikipedia/en/4/44/Her2013Poster.jpg" },
            { "The Fifth Element", "https://upload.wikimedia.org/wikipedia/en/6/65/Fifth_element_poster_%281997%29.jpg" },
            { "Total Recall", "https://upload.wikimedia.org/wikipedia/en/2/2d/Total_Recall_%281990_film%29_poster.jpg" },
            { "The Terminator", "https://upload.wikimedia.org/wikipedia/en/6/6d/The_Terminator.png" },
            { "Terminator 2: Judgment Day", "https://upload.wikimedia.org/wikipedia/en/5/5e/Terminator_2-Judgment_Day.png" },
            { "Edge of Tomorrow", "https://upload.wikimedia.org/wikipedia/en/f/f9/Edge_of_Tomorrow_Poster.jpg" },
            { "Minority Report", "https://upload.wikimedia.org/wikipedia/en/4/44/Minority_Report_Poster.jpg" },
            { "The Hunger Games", "https://upload.wikimedia.org/wikipedia/en/4/42/HungerGamesPoster.jpg" },
            { "Se7en", "https://upload.wikimedia.org/wikipedia/en/6/68/Seven_%28movie%29_poster.jpg" },
            { "Zodiac", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Ecliptic_path.jpg/330px-Ecliptic_path.jpg" },
            { "Shutter Island", "https://upload.wikimedia.org/wikipedia/en/a/a2/Shutter_Island_book_cover.jpg" },
            { "The Usual Suspects", "https://upload.wikimedia.org/wikipedia/en/9/9c/Usual_suspects_ver1.jpg" },
            { "No Country for Old Men", "https://upload.wikimedia.org/wikipedia/en/8/8b/No_Country_for_Old_Men_poster.jpg" },
            { "Goodfellas", "https://upload.wikimedia.org/wikipedia/en/7/7b/Goodfellas.jpg" },
            { "Reservoir Dogs", "https://upload.wikimedia.org/wikipedia/en/0/01/Reservoir_Dogs.png" },
            { "Heat", "https://upload.wikimedia.org/wikipedia/en/6/6c/Heatposter.jpg" },
            { "Gone Girl", "https://upload.wikimedia.org/wikipedia/en/0/05/Gone_Girl_Poster.jpg" },
            { "Prisoners", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Pentonvilleiso19.jpg/330px-Pentonvilleiso19.jpg" },
            { "The Menu", "https://upload.wikimedia.org/wikipedia/en/d/db/The_Menu_%282022_film%29.jpg" },
            { "The Shawshank Redemption", "https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg" },
            { "Schindler's List", "https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg" },
            { "The Green Mile", "https://upload.wikimedia.org/wikipedia/en/e/e2/The_Green_Mile_%28movie_poster%29.jpg" },
            { "Good Will Hunting", "https://upload.wikimedia.org/wikipedia/en/5/52/Good_Will_Hunting.png" },
            { "Dead Poets Society", "https://upload.wikimedia.org/wikipedia/en/8/86/Dead_poets_society.png" },
            { "A Beautiful Mind", "https://upload.wikimedia.org/wikipedia/en/b/b8/A_Beautiful_Mind_Poster.jpg" },
            { "Oppenheimer", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Oppenheimer_%28cropped%29.jpg/330px-Oppenheimer_%28cropped%29.jpg" },
            { "Dunkirk", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Dunkerque_hotel_de_ville_vu_port.jpg/330px-Dunkerque_hotel_de_ville_vu_port.jpg" },
            { "1917", "https://upload.wikimedia.org/wikipedia/en/thumb/f/fe/1917_%282019%29_Film_Poster.jpeg/330px-1917_%282019%29_Film_Poster.jpeg" },
            { "Full Metal Jacket", "https://upload.wikimedia.org/wikipedia/en/9/99/Full_Metal_Jacket_poster.jpg" },
            { "Apocalypse Now", "https://upload.wikimedia.org/wikipedia/en/c/c2/Apocalypse_Now_poster.jpg" },
            { "Hacksaw Ridge", "https://upload.wikimedia.org/wikipedia/en/8/8a/Hacksaw_Ridge_poster.png" },
            { "The Revenant", "https://upload.wikimedia.org/wikipedia/en/b/b6/The_Revenant_2015_film_poster.jpg" },
            { "Into the Wild", "https://upload.wikimedia.org/wikipedia/en/d/dc/Into_the_Wild_%282007_film_poster%29.png" },
            { "Cast Away", "https://upload.wikimedia.org/wikipedia/en/a/a7/Cast_away_film_poster.jpg" },
            { "Life of Pi", "https://upload.wikimedia.org/wikipedia/en/4/45/Life_of_Pi_cover.png" },
            { "Spirited Away", "https://upload.wikimedia.org/wikipedia/en/d/db/Spirited_Away_Japanese_poster.png" },
            { "Howl's Moving Castle", "https://upload.wikimedia.org/wikipedia/en/a/a0/Howls-moving-castleposter.jpg" },
            { "My Neighbor Totoro", "https://upload.wikimedia.org/wikipedia/en/0/02/My_Neighbor_Totoro_-_Tonari_no_Totoro_%28Movie_Poster%29.jpg" },
            { "Princess Mononoke", "https://upload.wikimedia.org/wikipedia/en/8/8c/Princess_Mononoke_Japanese_poster.png" },
            { "The Iron Giant", "https://upload.wikimedia.org/wikipedia/en/d/d3/The_Iron_Giant_poster.JPG" },
            { "Coraline", "https://upload.wikimedia.org/wikipedia/en/6/61/Coraline.jpg" },
            { "Despicable Me", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Despicable_Me_logo_2.svg/330px-Despicable_Me_logo_2.svg.png" },
            { "Inside Out", "https://upload.wikimedia.org/wikipedia/en/0/0a/Inside_Out_%282015_film%29_poster.jpg" },
            { "Coco", "https://upload.wikimedia.org/wikipedia/en/9/98/Coco_%282017_film%29_poster.jpg" },
            { "Casino Royale", "https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Casino_Royale_%282006_film_poster%29.jpg/330px-Casino_Royale_%282006_film_poster%29.jpg" },
            { "Skyfall", "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Skyfall_poster.jpg/330px-Skyfall_poster.jpg" },
            { "Mission: Impossible - Fallout", "https://upload.wikimedia.org/wikipedia/en/f/ff/MI_%E2%80%93_Fallout.jpg" },
            { "The Bourne Identity", "https://upload.wikimedia.org/wikipedia/en/4/49/The_Bourne_Identity_%282002%29_US_poster.jpg" },
            { "Taken", "https://upload.wikimedia.org/wikipedia/en/e/ed/Taken_film_poster.jpg" },
            { "The Equalizer", "https://upload.wikimedia.org/wikipedia/en/8/81/The_Equalizer_poster.jpg" },
            { "John Wick: Chapter 2", "https://upload.wikimedia.org/wikipedia/en/3/31/John_Wick_Chapter_Two.png" },
            { "Speed", "https://upload.wikimedia.org/wikipedia/en/4/45/Speed_movie_poster.jpg" },
            { "Lethal Weapon", "https://upload.wikimedia.org/wikipedia/en/d/d9/Lethal_weapon1.jpg" },
            { "Predator", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Polar_bear_%28Ursus_maritimus%29_with_its_prey.jpg/330px-Polar_bear_%28Ursus_maritimus%29_with_its_prey.jpg" },
            { "Crazy Rich Asians", "https://upload.wikimedia.org/wikipedia/en/b/ba/Crazy_Rich_Asians_poster.png" },
            { "The Proposal", "https://upload.wikimedia.org/wikipedia/en/0/02/The_Proposal.jpg" },
            { "500 Days of Summer", "https://upload.wikimedia.org/wikipedia/en/d/d1/Five_hundred_days_of_summer.jpg" },
            { "Silver Linings Playbook", "https://upload.wikimedia.org/wikipedia/en/9/9a/Silver_Linings_Playbook_Poster.jpg" },
            { "Eternal Sunshine of the Spotless Mind", "https://upload.wikimedia.org/wikipedia/en/a/a4/Eternal_Sunshine_of_the_Spotless_Mind.png" },
            { "The Fault in Our Stars", "https://upload.wikimedia.org/wikipedia/en/a/a9/The_Fault_in_Our_Stars.jpg" },
            { "Me Before You", "https://upload.wikimedia.org/wikipedia/en/f/fd/Me_Before_You_%28film%29.jpg" },
            { "Crazy, Stupid, Love", "https://upload.wikimedia.org/wikipedia/en/7/78/CrazyStupidLovePoster.jpg" },
            { "Bridesmaids", "https://upload.wikimedia.org/wikipedia/en/d/df/BridesmaidsPoster.jpg" },
            { "The Hangover", "https://upload.wikimedia.org/wikipedia/en/b/b9/Hangoverposter09.jpg" },
            { "21 Jump Street", "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/21_Jump_Street.png/330px-21_Jump_Street.png" },
            { "Deadpool", "https://upload.wikimedia.org/wikipedia/en/c/ca/Deadpool.png" },
            { "The 40-Year-Old Virgin", "https://upload.wikimedia.org/wikipedia/en/4/43/40-Year-OldVirginMoviePoster.jpg" },
            { "Talladega Nights", "https://upload.wikimedia.org/wikipedia/en/e/e7/Talladega_nights.jpg" },
            { "Elf", "https://upload.wikimedia.org/wikipedia/en/d/df/Elf_movie.jpg" },
            { "Groundhog Day", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Punxsutawney_Phil_Groundhog_Day_2022_Pennsylvania_%2851858203861%29.jpg/330px-Punxsutawney_Phil_Groundhog_Day_2022_Pennsylvania_%2851858203861%29.jpg" },
            { "The Breakfast Club", "https://upload.wikimedia.org/wikipedia/en/d/d1/The_Breakfast_Club_poster.jpg" },
            { "Ferris Bueller's Day Off", "https://upload.wikimedia.org/wikipedia/en/9/9b/Ferris_Bueller%27s_Day_Off.jpg" },
            { "Juno", "https://upload.wikimedia.org/wikipedia/en/3/36/Junoposter2007.png" },
            { "Little Miss Sunshine", "https://upload.wikimedia.org/wikipedia/en/1/16/Little_miss_sunshine_poster.jpg" },
            { "The Big Lebowski", "https://upload.wikimedia.org/wikipedia/en/3/35/Biglebowskiposter.jpg" },
            { "Gunpowder Milkshake", "https://upload.wikimedia.org/wikipedia/en/1/11/Gunpowder_Milkshake_%28poster%29.jpeg" },
            { "The Girl with All the Gifts", "https://upload.wikimedia.org/wikipedia/en/1/1f/The_Girl_with_All_the_Gifts.jpg" },
            { "Midori", "https://upload.wikimedia.org/wikipedia/en/c/cc/Sh%C5%8Djo_Tsubaki_cover.jpg" },
            { "A Serbian Film", "https://upload.wikimedia.org/wikipedia/en/d/de/Serbian-film-poster-325x460.jpg" },
            { "Salò, or the 120 Days of Sodom", "https://upload.wikimedia.org/wikipedia/en/f/f3/Saloposter.jpg" },
            { "Cannibal Holocaust", "https://upload.wikimedia.org/wikipedia/en/1/11/Cannibal_Holocaust_movie.jpg" },
            { "Akira", "https://upload.wikimedia.org/wikipedia/en/5/5d/AKIRA_%281988_poster%29.jpg" },
            { "Ghost in the Shell", "https://upload.wikimedia.org/wikipedia/en/c/ca/Ghostintheshellposter.jpg" },
            { "Your Name", "https://upload.wikimedia.org/wikipedia/en/0/0b/Your_Name_poster.png" },
            { "Perfect Blue", "https://upload.wikimedia.org/wikipedia/en/2/2a/Perfectblueposter.png" },
            { "Paprika", "https://upload.wikimedia.org/wikipedia/en/1/16/Paprikaposter.jpg" },
            { "The End of Evangelion", "https://upload.wikimedia.org/wikipedia/en/9/9e/Eoeposter.JPG" },
            { "Grave of the Fireflies", "https://upload.wikimedia.org/wikipedia/en/a/a5/Grave_of_the_Fireflies_Japanese_poster.jpg" },
            { "Nausicaä of the Valley of the Wind", "https://media.themoviedb.org/t/p/w342/tcrkfB8SRPQCgwI88hQScua6nxh.jpg" },
            { "Kiki's Delivery Service", "https://upload.wikimedia.org/wikipedia/en/0/07/Kiki%27s_Delivery_Service_%28Movie%29.jpg" },
            { "Ponyo", "https://upload.wikimedia.org/wikipedia/en/5/51/Ponyo.png" },
        };

        private static string FullPath(string appPath)
        {
            var relative = appPath.Replace('/', Path.DirectorySeparatorChar).TrimStart(Path.DirectorySeparatorChar);
            var roots = new[] { Directory.GetCurrentDirectory(), AppContext.BaseDirectory };
            foreach (var root in roots)
            {
                if (string.IsNullOrEmpty(root)) continue;
                var candidate = Path.Combine(root, "wwwroot", relative);
                if (File.Exists(candidate)) return candidate;
            }
            return null!;
        }

        public static string? UrlFor(string? title)
        {
            if (string.IsNullOrEmpty(title) || !Local.TryGetValue(title, out var local)) return null;
            return FullPath(local) != null ? local : (Remote.TryGetValue(title, out var remote) ? remote : null);
        }
    }
}
