using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using MvcMovie.Data;
using System;
using System.Linq;

namespace MvcMovie.Models;

public static class SeedData
{
    public static void Initialize(IServiceProvider serviceProvider)
    {
        using (var context = new MvcMovieContext(
            serviceProvider.GetRequiredService<
                DbContextOptions<MvcMovieContext>>()))
        {
            if (context.Movie.Any())
            {
                return; // DB already has data, stop seeding
            }

            context.Movie.AddRange(
                new Movie { Title = "When Harry Met Sally", ReleaseDate = DateTime.Parse("1989-2-12"), Genre = "Romantic Comedy", Price = 7.99M, Rating = "R" },
                new Movie { Title = "Ghostbusters 2", ReleaseDate = DateTime.Parse("1986-2-23"), Genre = "Comedy", Price = 9.99M, Rating = "PG" },
                new Movie { Title = "Rio Bravo", ReleaseDate = DateTime.Parse("1959-4-15"), Genre = "Western", Price = 3.99M, Rating = "R" },
                new Movie { Title = "Top Gun: Maverick", ReleaseDate = DateTime.Parse("2022-05-27"), Genre = "Action", Price = 9.99M, Rating = "PG-13" },
                new Movie { Title = "The Matrix", ReleaseDate = DateTime.Parse("1999-03-31"), Genre = "Sci-Fi", Price = 7.99M, Rating = "R" },
                new Movie { Title = "Interstellar", ReleaseDate = DateTime.Parse("2014-11-07"), Genre = "Sci-Fi", Price = 8.99M, Rating = "PG-13" },
                new Movie { Title = "Die Hard", ReleaseDate = DateTime.Parse("1988-07-15"), Genre = "Action", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Jurassic Park", ReleaseDate = DateTime.Parse("1993-06-11"), Genre = "Adventure", Price = 7.99M, Rating = "PG-13" },
                new Movie { Title = "Paddington 2", ReleaseDate = DateTime.Parse("2017-11-10"), Genre = "Family", Price = 4.99M, Rating = "PG" },
                new Movie { Title = "The Dark Knight", ReleaseDate = DateTime.Parse("2008-07-18"), Genre = "Action", Price = 8.99M, Rating = "PG-13" },
                new Movie { Title = "Shrek 2", ReleaseDate = DateTime.Parse("2004-05-19"), Genre = "Animation", Price = 6.99M, Rating = "PG" },
                new Movie { Title = "A Crown for Christmas", ReleaseDate = DateTime.Parse("2015-11-27"), Genre = "Romance", Price = 3.99M, Rating = "G" },
                new Movie { Title = "A Christmas Prince", ReleaseDate = DateTime.Parse("2017-11-10"), Genre = "Romance", Price = 3.99M, Rating = "PG" },
                new Movie { Title = "Inception", ReleaseDate = DateTime.Parse("2010-07-16"), Genre = "Sci-Fi", Price = 7.99M, Rating = "PG-13" },
                new Movie { Title = "Gladiator", ReleaseDate = DateTime.Parse("2000-05-05"), Genre = "Action", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Titanic", ReleaseDate = DateTime.Parse("1997-12-19"), Genre = "Romance", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "The Lord of the Rings: The Fellowship of the Ring", ReleaseDate = DateTime.Parse("2001-12-19"), Genre = "Fantasy", Price = 8.99M, Rating = "PG-13" },
                new Movie { Title = "Avatar", ReleaseDate = DateTime.Parse("2009-12-18"), Genre = "Sci-Fi", Price = 8.99M, Rating = "PG-13" },
                new Movie { Title = "Star Wars: Episode IV - A New Hope", ReleaseDate = DateTime.Parse("1977-05-25"), Genre = "Sci-Fi", Price = 7.99M, Rating = "PG" },
                new Movie { Title = "Pulp Fiction", ReleaseDate = DateTime.Parse("1994-10-14"), Genre = "Crime", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Fight Club", ReleaseDate = DateTime.Parse("1999-10-15"), Genre = "Drama", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Forrest Gump", ReleaseDate = DateTime.Parse("1994-07-06"), Genre = "Drama", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "The Godfather", ReleaseDate = DateTime.Parse("1972-03-24"), Genre = "Crime", Price = 7.99M, Rating = "R" },
                new Movie { Title = "The Silence of the Lambs", ReleaseDate = DateTime.Parse("1991-02-14"), Genre = "Thriller", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Saving Private Ryan", ReleaseDate = DateTime.Parse("1998-07-24"), Genre = "War", Price = 6.99M, Rating = "R" },
                new Movie { Title = "The Departed", ReleaseDate = DateTime.Parse("2006-10-06"), Genre = "Crime", Price = 7.99M, Rating = "R" },
                new Movie { Title = "Whiplash", ReleaseDate = DateTime.Parse("2014-10-10"), Genre = "Drama", Price = 6.99M, Rating = "R" },
                new Movie { Title = "The Prestige", ReleaseDate = DateTime.Parse("2006-10-20"), Genre = "Mystery", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "Memento", ReleaseDate = DateTime.Parse("2000-09-05"), Genre = "Mystery", Price = 5.99M, Rating = "R" },
                new Movie { Title = "The Lion King", ReleaseDate = DateTime.Parse("1994-06-24"), Genre = "Animation", Price = 6.99M, Rating = "G" },
                new Movie { Title = "Toy Story", ReleaseDate = DateTime.Parse("1995-11-22"), Genre = "Animation", Price = 5.99M, Rating = "G" },
                new Movie { Title = "Finding Nemo", ReleaseDate = DateTime.Parse("2003-05-30"), Genre = "Animation", Price = 6.99M, Rating = "G" },
                new Movie { Title = "Up", ReleaseDate = DateTime.Parse("2009-05-29"), Genre = "Animation", Price = 7.99M, Rating = "PG" },
                new Movie { Title = "WALL-E", ReleaseDate = DateTime.Parse("2008-06-27"), Genre = "Animation", Price = 7.99M, Rating = "G" },
                new Movie { Title = "Spider-Man: Into the Spider-Verse", ReleaseDate = DateTime.Parse("2018-12-14"), Genre = "Animation", Price = 8.99M, Rating = "PG" },
                new Movie { Title = "Spider-Man: Across the Spider-Verse", ReleaseDate = DateTime.Parse("2023-06-02"), Genre = "Animation", Price = 9.99M, Rating = "PG" },
                new Movie { Title = "The Avengers", ReleaseDate = DateTime.Parse("2012-05-04"), Genre = "Action", Price = 7.99M, Rating = "PG-13" },
                new Movie { Title = "Iron Man", ReleaseDate = DateTime.Parse("2008-05-02"), Genre = "Action", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "Captain America: The Winter Soldier", ReleaseDate = DateTime.Parse("2014-04-04"), Genre = "Action", Price = 7.99M, Rating = "PG-13" },
                new Movie { Title = "Logan", ReleaseDate = DateTime.Parse("2017-03-03"), Genre = "Action", Price = 7.99M, Rating = "R" },
                new Movie { Title = "Blade Runner 2049", ReleaseDate = DateTime.Parse("2017-10-06"), Genre = "Sci-Fi", Price = 8.99M, Rating = "R" },
                new Movie { Title = "Arrival", ReleaseDate = DateTime.Parse("2016-11-11"), Genre = "Sci-Fi", Price = 7.99M, Rating = "PG-13" },
                new Movie { Title = "Dune: Part One", ReleaseDate = DateTime.Parse("2021-10-22"), Genre = "Sci-Fi", Price = 9.99M, Rating = "PG-13" },
                new Movie { Title = "Dune: Part Two", ReleaseDate = DateTime.Parse("2024-03-01"), Genre = "Sci-Fi", Price = 9.99M, Rating = "PG-13" },
                new Movie { Title = "Mad Max: Fury Road", ReleaseDate = DateTime.Parse("2015-05-15"), Genre = "Action", Price = 7.99M, Rating = "R" },
                new Movie { Title = "John Wick", ReleaseDate = DateTime.Parse("2014-10-24"), Genre = "Action", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Baby Driver", ReleaseDate = DateTime.Parse("2017-06-28"), Genre = "Action", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Knives Out", ReleaseDate = DateTime.Parse("2019-11-27"), Genre = "Mystery", Price = 7.99M, Rating = "PG-13" },
                new Movie { Title = "Glass Onion", ReleaseDate = DateTime.Parse("2022-12-23"), Genre = "Mystery", Price = 8.99M, Rating = "PG-13" },
                new Movie { Title = "Parasite", ReleaseDate = DateTime.Parse("2019-11-08"), Genre = "Thriller", Price = 8.99M, Rating = "R" },
                new Movie { Title = "Everything Everywhere All at Once", ReleaseDate = DateTime.Parse("2022-04-08"), Genre = "Sci-Fi", Price = 8.99M, Rating = "R" },
                new Movie { Title = "La La Land", ReleaseDate = DateTime.Parse("2016-12-25"), Genre = "Musical", Price = 7.99M, Rating = "PG-13" },
                new Movie { Title = "The Truman Show", ReleaseDate = DateTime.Parse("1998-06-05"), Genre = "Comedy", Price = 5.99M, Rating = "PG" },
                new Movie { Title = "Back to the Future", ReleaseDate = DateTime.Parse("1985-07-03"), Genre = "Sci-Fi", Price = 6.99M, Rating = "PG" },
                new Movie { Title = "Ghostbusters", ReleaseDate = DateTime.Parse("1984-06-08"), Genre = "Comedy", Price = 5.99M, Rating = "PG" },
                new Movie { Title = "The Goonies", ReleaseDate = DateTime.Parse("1985-06-07"), Genre = "Adventure", Price = 5.99M, Rating = "PG" },
                new Movie { Title = "E.T. the Extra-Terrestrial", ReleaseDate = DateTime.Parse("1982-06-11"), Genre = "Sci-Fi", Price = 6.99M, Rating = "PG" },
                new Movie { Title = "Jaws", ReleaseDate = DateTime.Parse("1975-06-20"), Genre = "Thriller", Price = 5.99M, Rating = "PG" },
                new Movie { Title = "Alien", ReleaseDate = DateTime.Parse("1979-05-25"), Genre = "Horror", Price = 6.99M, Rating = "R" },
                new Movie { Title = "The Thing", ReleaseDate = DateTime.Parse("1982-06-25"), Genre = "Horror", Price = 5.99M, Rating = "R" },
                new Movie { Title = "The Shining", ReleaseDate = DateTime.Parse("1980-05-23"), Genre = "Horror", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Hereditary", ReleaseDate = DateTime.Parse("2018-06-08"), Genre = "Horror", Price = 7.99M, Rating = "R" },
                new Movie { Title = "Get Out", ReleaseDate = DateTime.Parse("2017-02-24"), Genre = "Horror", Price = 6.99M, Rating = "R" },
                new Movie { Title = "A Quiet Place", ReleaseDate = DateTime.Parse("2018-04-06"), Genre = "Horror", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "Superbad", ReleaseDate = DateTime.Parse("2007-08-17"), Genre = "Comedy", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Step Brothers", ReleaseDate = DateTime.Parse("2008-07-25"), Genre = "Comedy", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Anchorman", ReleaseDate = DateTime.Parse("2004-07-09"), Genre = "Comedy", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "Tropic Thunder", ReleaseDate = DateTime.Parse("2008-08-13"), Genre = "Comedy", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Hot Fuzz", ReleaseDate = DateTime.Parse("2007-02-14"), Genre = "Comedy", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Shaun of the Dead", ReleaseDate = DateTime.Parse("2004-04-09"), Genre = "Comedy", Price = 5.99M, Rating = "R" },
                new Movie { Title = "The Grand Budapest Hotel", ReleaseDate = DateTime.Parse("2014-03-28"), Genre = "Comedy", Price = 7.99M, Rating = "R" },
                new Movie { Title = "Knocked Up", ReleaseDate = DateTime.Parse("2007-06-01"), Genre = "Comedy", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Mean Girls", ReleaseDate = DateTime.Parse("2004-04-30"), Genre = "Comedy", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "Clueless", ReleaseDate = DateTime.Parse("1995-07-19"), Genre = "Comedy", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "10 Things I Hate About You", ReleaseDate = DateTime.Parse("1999-03-31"), Genre = "Romance", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "The Notebook", ReleaseDate = DateTime.Parse("2004-06-25"), Genre = "Romance", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "Pride and Prejudice", ReleaseDate = DateTime.Parse("2005-11-23"), Genre = "Romance", Price = 6.99M, Rating = "PG" },
                new Movie { Title = "About Time", ReleaseDate = DateTime.Parse("2013-09-04"), Genre = "Romance", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Little Women", ReleaseDate = DateTime.Parse("2019-12-25"), Genre = "Drama", Price = 7.99M, Rating = "PG" },
                new Movie { Title = "Lady Bird", ReleaseDate = DateTime.Parse("2017-11-03"), Genre = "Drama", Price = 6.99M, Rating = "R" },
                new Movie { Title = "The Social Network", ReleaseDate = DateTime.Parse("2010-10-01"), Genre = "Drama", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "Moneyball", ReleaseDate = DateTime.Parse("2011-09-23"), Genre = "Drama", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "The Wolf of Wall Street", ReleaseDate = DateTime.Parse("2013-12-25"), Genre = "Comedy", Price = 7.99M, Rating = "R" },
                new Movie { Title = "Catch Me If You Can", ReleaseDate = DateTime.Parse("2002-12-25"), Genre = "Biography", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "Zootopia", ReleaseDate = DateTime.Parse("2016-03-04"), Genre = "Animation", Price = 6.99M, Rating = "PG" },
                new Movie { Title = "Moana", ReleaseDate = DateTime.Parse("2016-11-23"), Genre = "Animation", Price = 6.99M, Rating = "PG" },
                new Movie { Title = "Frozen", ReleaseDate = DateTime.Parse("2013-11-27"), Genre = "Animation", Price = 6.99M, Rating = "PG" },
                new Movie { Title = "Tangled", ReleaseDate = DateTime.Parse("2010-11-24"), Genre = "Animation", Price = 6.99M, Rating = "PG" },
                new Movie { Title = "Ratatouille", ReleaseDate = DateTime.Parse("2007-06-29"), Genre = "Animation", Price = 6.99M, Rating = "G" },
                new Movie { Title = "The Incredibles", ReleaseDate = DateTime.Parse("2004-11-05"), Genre = "Animation", Price = 6.99M, Rating = "PG" },
                new Movie { Title = "Monsters, Inc.", ReleaseDate = DateTime.Parse("2001-11-02"), Genre = "Animation", Price = 5.99M, Rating = "G" },
                new Movie { Title = "Princess Switch", ReleaseDate = DateTime.Parse("2018-11-16"), Genre = "Romance", Price = 3.99M, Rating = "G" },
                new Movie { Title = "The Knight Before Christmas", ReleaseDate = DateTime.Parse("2019-11-21"), Genre = "Romance", Price = 3.99M, Rating = "PG" },
                new Movie { Title = "Operation Christmas Drop", ReleaseDate = DateTime.Parse("2020-11-05"), Genre = "Romance", Price = 3.99M, Rating = "TV-PG" },
                new Movie { Title = "Christmas Inheritance", ReleaseDate = DateTime.Parse("2017-12-15"), Genre = "Romance", Price = 3.99M, Rating = "TV-PG" },
                new Movie { Title = "Holidate", ReleaseDate = DateTime.Parse("2020-10-28"), Genre = "Romance", Price = 4.99M, Rating = "TV-MA" },
                new Movie { Title = "Love Hard", ReleaseDate = DateTime.Parse("2021-11-05"), Genre = "Romance", Price = 4.99M, Rating = "PG-13" },
                new Movie { Title = "Falling for Christmas", ReleaseDate = DateTime.Parse("2022-11-10"), Genre = "Romance", Price = 4.99M, Rating = "PG" },
                new Movie { Title = "Hot Frosty", ReleaseDate = DateTime.Parse("2024-11-13"), Genre = "Romance", Price = 3.99M, Rating = "TV-14" },
                new Movie { Title = "The Merry Gentlemen", ReleaseDate = DateTime.Parse("2024-11-20"), Genre = "Romance", Price = 3.99M, Rating = "TV-MA" },
                new Movie { Title = "The Exorcist", ReleaseDate = DateTime.Parse("1973-12-26"), Genre = "Horror", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Halloween", ReleaseDate = DateTime.Parse("1978-10-25"), Genre = "Horror", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Scream", ReleaseDate = DateTime.Parse("1996-12-20"), Genre = "Horror", Price = 5.99M, Rating = "R" },
                new Movie { Title = "A Nightmare on Elm Street", ReleaseDate = DateTime.Parse("1984-11-09"), Genre = "Horror", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Friday the 13th", ReleaseDate = DateTime.Parse("1980-05-09"), Genre = "Horror", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Psycho", ReleaseDate = DateTime.Parse("1960-09-08"), Genre = "Horror", Price = 4.99M, Rating = "R" },
                new Movie { Title = "The Ring", ReleaseDate = DateTime.Parse("2002-10-18"), Genre = "Horror", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "The Grudge", ReleaseDate = DateTime.Parse("2004-10-22"), Genre = "Horror", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "Saw", ReleaseDate = DateTime.Parse("2004-10-29"), Genre = "Horror", Price = 5.99M, Rating = "R" },
                new Movie { Title = "The Texas Chainsaw Massacre", ReleaseDate = DateTime.Parse("1974-10-01"), Genre = "Horror", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Rosemary's Baby", ReleaseDate = DateTime.Parse("1968-06-12"), Genre = "Horror", Price = 5.99M, Rating = "R" },
                new Movie { Title = "The Blair Witch Project", ReleaseDate = DateTime.Parse("1999-07-30"), Genre = "Horror", Price = 5.99M, Rating = "R" },
                new Movie { Title = "The Conjuring", ReleaseDate = DateTime.Parse("2013-07-19"), Genre = "Horror", Price = 7.99M, Rating = "R" },
                new Movie { Title = "Insidious", ReleaseDate = DateTime.Parse("2011-04-01"), Genre = "Horror", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "It", ReleaseDate = DateTime.Parse("2017-09-08"), Genre = "Horror", Price = 7.99M, Rating = "R" },
                new Movie { Title = "Us", ReleaseDate = DateTime.Parse("2019-03-22"), Genre = "Horror", Price = 7.99M, Rating = "R" },
                new Movie { Title = "Midsommar", ReleaseDate = DateTime.Parse("2019-07-03"), Genre = "Horror", Price = 7.99M, Rating = "R" },
                new Movie { Title = "The Witch", ReleaseDate = DateTime.Parse("2015-10-11"), Genre = "Horror", Price = 6.99M, Rating = "R" },
                new Movie { Title = "The Martian", ReleaseDate = DateTime.Parse("2015-10-02"), Genre = "Sci-Fi", Price = 7.99M, Rating = "PG-13" },
                new Movie { Title = "Project Hail Mary", ReleaseDate = DateTime.Parse("2026-03-20"), Genre = "Sci-Fi", Price = 9.99M, Rating = "PG-13" },
                new Movie { Title = "Men in Black", ReleaseDate = DateTime.Parse("1997-07-02"), Genre = "Sci-Fi", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "Gravity", ReleaseDate = DateTime.Parse("2013-10-04"), Genre = "Sci-Fi", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "Sunshine", ReleaseDate = DateTime.Parse("2007-04-05"), Genre = "Sci-Fi", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Moon", ReleaseDate = DateTime.Parse("2009-06-12"), Genre = "Sci-Fi", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Ex Machina", ReleaseDate = DateTime.Parse("2015-01-21"), Genre = "Sci-Fi", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Her", ReleaseDate = DateTime.Parse("2013-12-18"), Genre = "Sci-Fi", Price = 7.99M, Rating = "R" },
                new Movie { Title = "The Fifth Element", ReleaseDate = DateTime.Parse("1997-05-09"), Genre = "Sci-Fi", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "Total Recall", ReleaseDate = DateTime.Parse("1990-06-01"), Genre = "Sci-Fi", Price = 6.99M, Rating = "R" },
                new Movie { Title = "The Terminator", ReleaseDate = DateTime.Parse("1984-10-26"), Genre = "Sci-Fi", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Terminator 2: Judgment Day", ReleaseDate = DateTime.Parse("1991-07-03"), Genre = "Sci-Fi", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Edge of Tomorrow", ReleaseDate = DateTime.Parse("2014-06-06"), Genre = "Sci-Fi", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "Minority Report", ReleaseDate = DateTime.Parse("2002-06-21"), Genre = "Sci-Fi", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "The Hunger Games", ReleaseDate = DateTime.Parse("2012-03-23"), Genre = "Sci-Fi", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "Se7en", ReleaseDate = DateTime.Parse("1995-09-22"), Genre = "Crime", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Zodiac", ReleaseDate = DateTime.Parse("2007-03-02"), Genre = "Mystery", Price = 7.99M, Rating = "R" },
                new Movie { Title = "Shutter Island", ReleaseDate = DateTime.Parse("2010-02-19"), Genre = "Mystery", Price = 6.99M, Rating = "R" },
                new Movie { Title = "The Usual Suspects", ReleaseDate = DateTime.Parse("1995-08-16"), Genre = "Crime", Price = 6.99M, Rating = "R" },
                new Movie { Title = "No Country for Old Men", ReleaseDate = DateTime.Parse("2007-11-09"), Genre = "Crime", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Goodfellas", ReleaseDate = DateTime.Parse("1990-09-19"), Genre = "Crime", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Reservoir Dogs", ReleaseDate = DateTime.Parse("1992-10-23"), Genre = "Crime", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Heat", ReleaseDate = DateTime.Parse("1995-12-15"), Genre = "Crime", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Gone Girl", ReleaseDate = DateTime.Parse("2014-10-03"), Genre = "Thriller", Price = 7.99M, Rating = "R" },
                new Movie { Title = "Prisoners", ReleaseDate = DateTime.Parse("2013-09-20"), Genre = "Thriller", Price = 7.99M, Rating = "R" },
                new Movie { Title = "The Menu", ReleaseDate = DateTime.Parse("2022-11-18"), Genre = "Thriller", Price = 7.99M, Rating = "R" },
                new Movie { Title = "The Shawshank Redemption", ReleaseDate = DateTime.Parse("1994-09-23"), Genre = "Drama", Price = 7.99M, Rating = "R" },
                new Movie { Title = "Schindler's List", ReleaseDate = DateTime.Parse("1993-12-15"), Genre = "Biography", Price = 7.99M, Rating = "R" },
                new Movie { Title = "The Green Mile", ReleaseDate = DateTime.Parse("1999-12-10"), Genre = "Drama", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Good Will Hunting", ReleaseDate = DateTime.Parse("1997-12-05"), Genre = "Drama", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Dead Poets Society", ReleaseDate = DateTime.Parse("1989-06-09"), Genre = "Drama", Price = 5.99M, Rating = "PG" },
                new Movie { Title = "A Beautiful Mind", ReleaseDate = DateTime.Parse("2001-12-21"), Genre = "Biography", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "Oppenheimer", ReleaseDate = DateTime.Parse("2023-07-21"), Genre = "Biography", Price = 9.99M, Rating = "R" },
                new Movie { Title = "Dunkirk", ReleaseDate = DateTime.Parse("2017-07-21"), Genre = "War", Price = 7.99M, Rating = "PG-13" },
                new Movie { Title = "1917", ReleaseDate = DateTime.Parse("2019-12-25"), Genre = "War", Price = 7.99M, Rating = "R" },
                new Movie { Title = "Full Metal Jacket", ReleaseDate = DateTime.Parse("1987-06-26"), Genre = "War", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Apocalypse Now", ReleaseDate = DateTime.Parse("1979-08-15"), Genre = "War", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Hacksaw Ridge", ReleaseDate = DateTime.Parse("2016-11-04"), Genre = "War", Price = 6.99M, Rating = "R" },
                new Movie { Title = "The Revenant", ReleaseDate = DateTime.Parse("2015-12-25"), Genre = "Adventure", Price = 7.99M, Rating = "R" },
                new Movie { Title = "Into the Wild", ReleaseDate = DateTime.Parse("2007-09-21"), Genre = "Adventure", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Cast Away", ReleaseDate = DateTime.Parse("2000-12-22"), Genre = "Adventure", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "Life of Pi", ReleaseDate = DateTime.Parse("2012-11-21"), Genre = "Adventure", Price = 7.99M, Rating = "PG" },
                new Movie { Title = "Spirited Away", ReleaseDate = DateTime.Parse("2001-07-20"), Genre = "Animation", Price = 6.99M, Rating = "PG" },
                new Movie { Title = "Howl's Moving Castle", ReleaseDate = DateTime.Parse("2004-09-05"), Genre = "Animation", Price = 6.99M, Rating = "PG" },
                new Movie { Title = "My Neighbor Totoro", ReleaseDate = DateTime.Parse("1988-04-16"), Genre = "Animation", Price = 5.99M, Rating = "G" },
                new Movie { Title = "Princess Mononoke", ReleaseDate = DateTime.Parse("1997-07-12"), Genre = "Animation", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "The Iron Giant", ReleaseDate = DateTime.Parse("1999-08-06"), Genre = "Animation", Price = 5.99M, Rating = "PG" },
                new Movie { Title = "Coraline", ReleaseDate = DateTime.Parse("2009-02-06"), Genre = "Animation", Price = 5.99M, Rating = "PG" },
                new Movie { Title = "Despicable Me", ReleaseDate = DateTime.Parse("2010-07-09"), Genre = "Animation", Price = 6.99M, Rating = "PG" },
                new Movie { Title = "Inside Out", ReleaseDate = DateTime.Parse("2015-06-19"), Genre = "Animation", Price = 7.99M, Rating = "PG" },
                new Movie { Title = "Coco", ReleaseDate = DateTime.Parse("2017-11-22"), Genre = "Animation", Price = 7.99M, Rating = "PG" },
                new Movie { Title = "Casino Royale", ReleaseDate = DateTime.Parse("2006-11-17"), Genre = "Action", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "Skyfall", ReleaseDate = DateTime.Parse("2012-10-26"), Genre = "Action", Price = 7.99M, Rating = "PG-13" },
                new Movie { Title = "Mission: Impossible - Fallout", ReleaseDate = DateTime.Parse("2018-07-27"), Genre = "Action", Price = 7.99M, Rating = "PG-13" },
                new Movie { Title = "The Bourne Identity", ReleaseDate = DateTime.Parse("2002-06-14"), Genre = "Action", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "Taken", ReleaseDate = DateTime.Parse("2008-02-27"), Genre = "Action", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "The Equalizer", ReleaseDate = DateTime.Parse("2014-09-26"), Genre = "Action", Price = 6.99M, Rating = "R" },
                new Movie { Title = "John Wick: Chapter 2", ReleaseDate = DateTime.Parse("2017-02-10"), Genre = "Action", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Speed", ReleaseDate = DateTime.Parse("1994-06-10"), Genre = "Action", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Lethal Weapon", ReleaseDate = DateTime.Parse("1987-03-06"), Genre = "Action", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Predator", ReleaseDate = DateTime.Parse("1987-06-12"), Genre = "Action", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Crazy Rich Asians", ReleaseDate = DateTime.Parse("2018-08-15"), Genre = "Romance", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "The Proposal", ReleaseDate = DateTime.Parse("2009-06-19"), Genre = "Romance", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "500 Days of Summer", ReleaseDate = DateTime.Parse("2009-08-07"), Genre = "Romance", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "Silver Linings Playbook", ReleaseDate = DateTime.Parse("2012-11-16"), Genre = "Romance", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Eternal Sunshine of the Spotless Mind", ReleaseDate = DateTime.Parse("2004-03-19"), Genre = "Romance", Price = 6.99M, Rating = "R" },
                new Movie { Title = "The Fault in Our Stars", ReleaseDate = DateTime.Parse("2014-06-06"), Genre = "Romance", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "Me Before You", ReleaseDate = DateTime.Parse("2016-06-03"), Genre = "Romance", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "Crazy, Stupid, Love", ReleaseDate = DateTime.Parse("2011-07-29"), Genre = "Romance", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "Bridesmaids", ReleaseDate = DateTime.Parse("2011-05-13"), Genre = "Comedy", Price = 5.99M, Rating = "R" },
                new Movie { Title = "The Hangover", ReleaseDate = DateTime.Parse("2009-06-05"), Genre = "Comedy", Price = 5.99M, Rating = "R" },
                new Movie { Title = "21 Jump Street", ReleaseDate = DateTime.Parse("2012-03-16"), Genre = "Comedy", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Deadpool", ReleaseDate = DateTime.Parse("2016-02-12"), Genre = "Comedy", Price = 6.99M, Rating = "R" },
                new Movie { Title = "The 40-Year-Old Virgin", ReleaseDate = DateTime.Parse("2005-08-19"), Genre = "Comedy", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Talladega Nights", ReleaseDate = DateTime.Parse("2006-08-04"), Genre = "Comedy", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "Elf", ReleaseDate = DateTime.Parse("2003-11-07"), Genre = "Comedy", Price = 5.99M, Rating = "PG" },
                new Movie { Title = "Groundhog Day", ReleaseDate = DateTime.Parse("1993-02-12"), Genre = "Comedy", Price = 5.99M, Rating = "PG" },
                new Movie { Title = "The Breakfast Club", ReleaseDate = DateTime.Parse("1985-02-15"), Genre = "Comedy", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Ferris Bueller's Day Off", ReleaseDate = DateTime.Parse("1986-06-11"), Genre = "Comedy", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "Juno", ReleaseDate = DateTime.Parse("2007-12-05"), Genre = "Comedy", Price = 5.99M, Rating = "PG-13" },
                new Movie { Title = "Little Miss Sunshine", ReleaseDate = DateTime.Parse("2006-08-18"), Genre = "Comedy", Price = 5.99M, Rating = "R" },
                new Movie { Title = "The Big Lebowski", ReleaseDate = DateTime.Parse("1998-03-06"), Genre = "Comedy", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Gunpowder Milkshake", ReleaseDate = DateTime.Parse("2021-07-14"), Genre = "Action", Price = 6.99M, Rating = "R" },
                new Movie { Title = "The Girl with All the Gifts", ReleaseDate = DateTime.Parse("2016-09-23"), Genre = "Sci-Fi", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Midori", ReleaseDate = DateTime.Parse("1992-05-02"), Genre = "Animation", Price = 7.99M, Rating = "NR" },
                new Movie { Title = "A Serbian Film", ReleaseDate = DateTime.Parse("2010-06-11"), Genre = "Horror", Price = 6.99M, Rating = "TV-MA" },
                new Movie { Title = "Salò, or the 120 Days of Sodom", ReleaseDate = DateTime.Parse("1976-01-10"), Genre = "Drama", Price = 5.99M, Rating = "TV-MA" },
                new Movie { Title = "Cannibal Holocaust", ReleaseDate = DateTime.Parse("1980-02-07"), Genre = "Horror", Price = 5.99M, Rating = "TV-MA" },
                new Movie { Title = "Akira", ReleaseDate = DateTime.Parse("1988-07-16"), Genre = "Animation", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Ghost in the Shell", ReleaseDate = DateTime.Parse("1995-11-18"), Genre = "Animation", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Your Name", ReleaseDate = DateTime.Parse("2016-08-26"), Genre = "Animation", Price = 6.99M, Rating = "PG" },
                new Movie { Title = "Perfect Blue", ReleaseDate = DateTime.Parse("1997-02-28"), Genre = "Animation", Price = 5.99M, Rating = "R" },
                new Movie { Title = "Paprika", ReleaseDate = DateTime.Parse("2006-11-25"), Genre = "Animation", Price = 5.99M, Rating = "R" },
                new Movie { Title = "The End of Evangelion", ReleaseDate = DateTime.Parse("1997-07-19"), Genre = "Animation", Price = 6.99M, Rating = "R" },
                new Movie { Title = "Grave of the Fireflies", ReleaseDate = DateTime.Parse("1988-04-16"), Genre = "Animation", Price = 6.99M, Rating = "PG-13" },
                new Movie { Title = "Nausicaä of the Valley of the Wind", ReleaseDate = DateTime.Parse("1984-03-11"), Genre = "Animation", Price = 6.99M, Rating = "PG" },
                new Movie { Title = "Kiki's Delivery Service", ReleaseDate = DateTime.Parse("1989-07-29"), Genre = "Animation", Price = 5.99M, Rating = "G" },
                new Movie { Title = "Ponyo", ReleaseDate = DateTime.Parse("2008-07-19"), Genre = "Animation", Price = 5.99M, Rating = "G" }
            );
            context.SaveChanges();
        }
    }
}
